In [ ]:
import pandas as pd
from google.colab import files
files = files.upload()

Saving aus_amon_final.csv to aus_amon_final.csv

In [ ]:
df = pd.read_csv('aus_amon_final.csv')
df.dropna(subset = ['Aus_Area', 'Aus_Production', 'Amon_Area','Amon_Production'],axis = 0,inplace = True)
df.drop(['Unnamed: 0'],axis =1 ,inplace = True)
df

     Station Names  YEAR  ...     Amon_Area  Amon_Production
2            Bogra  1970  ...  634460.00000    254832.802425
4       Chittagong  1970  ...  497290.00000    289460.053875
5          Comilla  1970  ...  976420.00000    461126.671425
7            Dhaka  1970  ...  765390.00000    283694.893200
8         Dinajpur  1970  ...  888530.00000    369283.262025
...            ...   ...  ...           ...              ...
1551     Rangamati  2016  ...   24596.83170     28235.000000
1552       Rangpur  2016  ...  386482.10420    435771.000000
1554      Satkhira  2016  ...  230825.72260    282279.000000
1558        Sylhet  2016  ...  315849.61100    279939.000000
1559       Tangail  2016  ...  313133.92705    277697.000000

[914 rows x 13 columns]

In [ ]:
df = df.sort_values(["YEAR"], ascending=True,ignore_index = True)
df

    Station Names  YEAR  ...     Amon_Area  Amon_Production
0           Bogra  1970  ...  6.344600e+05    254832.802425
1         Rangpur  1970  ...  1.209490e+06    564291.749625
2        Rajshahi  1970  ...  1.111420e+06    493885.121775
3      Mymensingh  1970  ...  1.501670e+06    623408.460150
4          Khulna  1970  ...  1.007020e+06    397043.123025
..            ...   ...  ...           ...              ...
909      Rajshahi  2018  ...  4.385881e+05    196177.000000
910     Rangamati  2018  ...  6.078000e+04     25136.000000
911       Rangpur  2018  ...  9.550166e+05    461649.000000
912      Faridpur  2018  ...  3.704014e+05    198852.000000
913       Tangail  2018  ...  7.737696e+05    250133.000000

[914 rows x 13 columns]

In [ ]:
df_d=df[df['Station Names'].str.contains("Dhaka")]
df_d.to_csv("new_dhaka.csv")

In [ ]:
df = df.drop(['Station Names'], axis=1)
train=df[:635]
test=df[635:]
print(train,test)

     YEAR   Max Temp   Min Temp  ...  Bright Sunshine  Aus_Area  Aus_Production
0    1970  35.758333  20.925000  ...         7.541667    286080    86400.299400
1    1970  33.558333  18.891667  ...         6.424762    906800   294821.517225
2    1970  32.266667  20.525000  ...         6.820238    474080   157723.184100
3    1970  32.941667  20.750000  ...         5.892619   1089970   295456.546725
4    1970  34.925000  22.450000  ...         6.618889    119700    44556.391275
..    ...        ...        ...  ...              ...       ...             ...
630  2007  34.250000  20.375000  ...         6.183333     19260    14343.000000
631  2007  33.200000  21.408333  ...         5.683333     34435    25262.000000
632  2007  34.100000  21.391667  ...         6.100000     41920    12678.000000
633  2007  33.900000  21.783333  ...         5.508333      3490     1239.000000
634  2007  33.525000  22.300000  ...         6.591667      1725     1897.000000

[635 rows x 10 columns]      YEAR   Max Temp   Min Temp  ...  Bright Sunshine  Aus_Area  Aus_Production
635  2007  33.233333  21.066667  ...         5.775000    116225         90069.0
636  2007  34.916667  20.650000  ...         6.191667     20660         15796.0
637  2007  34.508333  21.800000  ...         6.150000     91835         86859.0
638  2007  33.816667  21.950000  ...         5.375000     37490         24838.0
639  2007  34.591667  21.075000  ...         5.391667     20940         15891.0
..    ...        ...        ...  ...              ...       ...             ...
841  2015  30.936667  20.968333  ...         4.826667     56081         52125.0
842  2015  30.805833  21.723333  ...         4.778333    184434        100811.0
843  2015  30.890000  21.795833  ...         4.899167     83188         49083.0
844  2015  30.238333  20.392500  ...         5.275000     12067         11216.0
845  2015  30.896667  20.436667  ...         5.613333       902           546.0

[211 rows x 10 columns]

In [ ]:
train.to_csv("train.csv")

In [ ]:
test.to_csv("test.csv")

In [ ]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 9 to 835
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Station Names      46 non-null     object
 1   YEAR               46 non-null     int64
 2   Max Temp           46 non-null     float64
 3   Min Temp           46 non-null     float64
 4   Rainfall           46 non-null     float64
 5   Relative Humidity  46 non-null     float64
 6   Wind Speed         46 non-null     float64
 7   Cloud Coverage     46 non-null     float64
 8   Bright Sunshine    46 non-null     float64
 9   Aus_Area           46 non-null     int64
 10  Aus_Production     46 non-null     float64
dtypes: float64(8), int64(2), object(1)
memory usage: 4.3+ KB

In [ ]:
train_d = df_d[:40]
test_d = df_d[40:]
print(train_d,test_d)

    Station Names  YEAR   Max Temp  ...  Bright Sunshine  Aus_Area  Aus_Production
9           Dhaka  1970  33.258333  ...         7.841667    499125   167860.976475
20          Dhaka  1971  32.125000  ...         7.025000    400750   131813.980500
30          Dhaka  1972  33.783333  ...         7.000000    406315   136336.297725
40          Dhaka  1973  33.108333  ...         7.733333    360745    94859.799525
62          Dhaka  1974  31.450000  ...         7.791667    385775   125499.972900
77          Dhaka  1975  32.975000  ...         8.016667    428705   140082.971775
91          Dhaka  1976  33.333333  ...         8.166667    414945   137982.838500
104         Dhaka  1977  32.800000  ...         7.250000    406025   139806.280350
118         Dhaka  1978  33.791667  ...         6.933333    394620   147812.187975
129         Dhaka  1979  33.575000  ...         7.058333    380420   145204.031100
146         Dhaka  1980  33.308333  ...         6.991667    376830   135596.941950
159         Dhaka  1981  33.441667  ...         6.758333    432070   147571.783950
183         Dhaka  1982  33.808333  ...         6.783333    417890   162481.369425
199         Dhaka  1983  33.508333  ...         6.791667    405185   164654.077500
216         Dhaka  1984  33.800000  ...         6.691667    428525   174832.693200
233         Dhaka  1985  34.075000  ...         6.983333    385010   144872.001390
243         Dhaka  1986  34.566667  ...         7.150000    282855   112207.898280
257         Dhaka  1987  35.116667  ...         7.208333    329715   130503.098175
286         Dhaka  1988  34.475000  ...         6.758333    283530    31933.819185
302         Dhaka  1989  34.641667  ...         7.083333    324355    98665.440600
327         Dhaka  1990  32.958333  ...         7.025000    263270    99314.077875
340         Dhaka  1991  33.666667  ...         7.025000    224780    81238.416750
360         Dhaka  1992  33.591667  ...         6.866667    188450    66378.726450
367         Dhaka  1993  33.066667  ...         6.166667    188450    66378.726450
394         Dhaka  1994  33.683333  ...         6.541667    169980    55964.242650
405         Dhaka  1995  34.466667  ...         6.216667    161180    49904.246850
433         Dhaka  1996  34.641667  ...         6.716667     14490     7366.342200
448         Dhaka  1997  33.625000  ...         6.233333    138610    44560.927200
458         Dhaka  1998  33.866667  ...         5.825000    141200    41712.366300
483         Dhaka  1999  34.483333  ...         6.166667    117890    33892.431600
502         Dhaka  2000  33.091667  ...         6.250000    123520    37185.513150
522         Dhaka  2001  33.241667  ...         6.291667    117280    40070.361450
539         Dhaka  2002  33.441667  ...         5.958333    114850    44034.759900
556         Dhaka  2003  33.516667  ...         5.883333    108390    38546.290650
573         Dhaka  2004  33.550000  ...         5.908333    107500    42038.952900
593         Dhaka  2005  33.666667  ...         5.925000     57420    20665.674300
610         Dhaka  2006  34.616667  ...         5.650000     35870    15892.066830
633         Dhaka  2007  33.900000  ...         5.508333      3490     1239.000000
653         Dhaka  2008  33.675000  ...         5.566667      1960      804.000000
678         Dhaka  2009  34.658333  ...         6.066667      2780     1492.000000

[40 rows x 11 columns]     Station Names  YEAR   Max Temp  ...  Bright Sunshine  Aus_Area  Aus_Production
716         Dhaka  2010  34.241667  ...         5.783333      2227          1353.0
730         Dhaka  2011  33.658333  ...         5.283333      1607           912.0
758         Dhaka  2012  34.116667  ...         5.158333      1552           927.0
793         Dhaka  2013  34.175000  ...         5.100000      1241           752.0
815         Dhaka  2014  31.128333  ...         5.285833      1178           947.0
835         Dhaka  2015  30.892500  ...         5.223333      1711          1413.0

[6 rows x 11 columns]

In [ ]:
train_d.to_csv("train_dhaka.csv")
test_d.to_csv("test_dhaka.csv")

In [1]:
from google.colab import files
files = files.upload()

Saving sorted year and station names.csv to sorted year and station names.csv

In [2]:
import pandas as pd
df = pd.read_csv("sorted year and station names.csv", index_col = 0)

In [ ]:
df2 = df.to_excel("sorted year and station names.xlsx")

In [ ]:
df.dropna(axis =0, inplace = True)

In [4]:
df.dtypes

Unnamed: 0.1           int64
Station Names         object
YEAR                   int64
Max Temp             float64
Min Temp             float64
Rainfall             float64
Relative Humidity    float64
Wind Speed           float64
Cloud Coverage       float64
Bright Sunshine      float64
Aus_Area             float64
Aus_Production       float64
Amon_Area            float64
Amon_Production      float64
Boro_Area            float64
Boro_Production      float64
dtype: object

In [3]:
df.isnull().sum()

Unnamed: 0.1           0
Station Names          0
YEAR                   0
Max Temp               0
Min Temp               0
Rainfall               0
Relative Humidity      1
Wind Speed             1
Cloud Coverage         1
Bright Sunshine        1
Aus_Area             646
Aus_Production       646
Amon_Area            644
Amon_Production      644
Boro_Area            647
Boro_Production      647
dtype: int64

In [ ]:
avg_temp = df[['Max Temp', 'Min Temp']].mean(axis=1)
avg_temp

2       28.341667
4       26.958333
5       27.645833
7       27.362500
8       27.025000
          ...
1516    25.636667
1517    25.206667
1519    26.457083
1523    25.737083
1524    25.805000
Length: 909, dtype: float64

In [ ]:
df2 = df.assign(AvgTemp=avg_temp)
df2.to_excel("Data.xlsx")

In [ ]:
df3 = df.to_excel("sorted drop nun value.xlsx")